### ISSUE TITLE
we can probably get this working in collab

### ISSUE THREAD

**Issue by kushalkolar** [vispy/jupyter_rfb#74]
@manzt figured this out at scipy!

Logging this here to work on when I have time.

Basically:

1. collab-specific metadata has to be returned by `_repr_mimebundle`,
2. publish `jupyter-rfb` to `npm` so collab can find it, because collab doesn't use local js. Outline of a CI action to do this:

```yaml
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - run: |
          python -m pip install --upgrade pip
          pip install build twine
          python -m build
          twine upload dist/*
       
      - uses: actions/setup-node
        with:
          node-version: 18
        run: |
          cd js
          npm publish
```
